#! /usr/bin/env perl

use strict;
use Getopt::ArgvFile home=>1;
use Getopt::Long;
use Cwd;
use Cwd 'chdir';

my $user;
my $passwd;
my $artUrl;
my $debug;
my $newTool;
my $noXmessage;
my $help;

GetOptions("user=s" => \$user,
           "passwd=s" => \$passwd,
           "artUrl=s" => \$artUrl,
           "debug" =>\$debug,
           "noxmessage" =>\$noXmessage,
           "help|?" => \$help,
    ) or printHelp();

printHelp() if($help);

sub printHelp
{
  print("\nWrapper for ebu's artifactory tool. By default this script will read a config\n");
  print("file: ~/.3rdpartyArtifactory , for comand line options set there. For example\n");
  print("you can put:\n--user foo\n--passwd ...\n--artUrl http..\nIn the config file which\n");
  print("the script will read first. If you put command line options, these will override\n");
  print("whatever is in the config file.\n");
  print("\n3rdpartyArtifactory [--user <user>] [--passwd <passwd>]\n");
  print("\t[--artUrl <artifactory URL>] [--debug] [--noxmessage] [--help] \n");
  exit(1);
}

if(!-f "/usr/bin/xmessage") {
  $noXmessage = 1;
}

my $crappyEBUtool;
if(-d "bldtools") {
  # old bldtools stuff
  $crappyEBUtool = "./bldtools/3rdparty-af/ebuartifact.sh";
} elsif (-d "DevTools") {
  # new crappy 3rdparty tool
  my $newCrappy3rdpartyTool = 
      "./DevTools/utilities/thirdparty_artifactory/thirdparty_download.sh";
  if(-f $newCrappy3rdpartyTool) {
    $crappyEBUtool = $newCrappy3rdpartyTool;
  } else {
    $crappyEBUtool = "./DevTools/utilities/3rdparty-af/ebuartifact.sh";
  }
} else {
  print("\nERROR: no tools directory, either bldtools or DevTools.\n\t");
  print("\tMake sure you are in the directory above the repo's\n");
  exit(5);
}

if(! -e $crappyEBUtool) {
  print("\nERROR: cannot find ebu tool: $crappyEBUtool\n");
  print("\tMake sure you are in the directory above the repo's\n");
  exit(1);
}
print("\nINFO: using $crappyEBUtool\n\n");
chomp($user);
chomp($passwd);
chomp($artUrl);

print("\nUsing username: $user\n");
print("artifactory URL: $artUrl\n");

print("Checking username/passwd as the crappy ebu tool does not do this\n");
my $silent = " -s ";
if($debug) {
  $silent = " ";
}
# my $cmd = "curl -k $silent -u ${user}:${passwd} $artUrl";
# my $output = qx/$cmd 2>&1/;
# if($?) {
#   print("ERROR: curl failed with the following output:\n\n");
#   print("$output\n\n");
#   exit(5);
# }
# if($debug) {
#   print("$cmd returned $output\n");
# }
# if($output =~ m/401/) {
#   if($output =~ m/Bad credentials/) {
#     print("\nERROR: bad credentails, check passwd\n\n");
#     exit(3);
#   } else {
#     print("\nERROR: Recieved 401 in output: \n");
#     print("$output\n\n");
#     exit(4);
#   }
# }

# if($output =~ m/404/) {
#   print("\nERROR: $artUrl is down....\n\n");
#   print("$output\n\n");
#   exit(3);
# }


print("running $crappyEBUtool\n\n");
my $debugSwitch = " ";
if($debug) {
  $debugSwitch = " -d ";
}
my $cmd = "$crappyEBUtool -u $user -p $passwd -s $artUrl $debugSwitch";
print("\nRunning command: \n$cmd\n\n");
my $ret = system($cmd);
print("\nCommand returned: $ret ...\n");
my $cwd = getcwd();
my $output = "SUCCESS: 3rdpartyArtifactory completed in ";
if($ret != 0) {
  $output = "FAILED: 3rdpartyArtifactory failed in ";
  $ret = 1;
  print("\n\n$output $cwd\n\n");
  if(! $noXmessage) {
    my $cmd = "xmessage -center \"${output} $cwd\"";
  }
  exit($ret);
}
my $kernelName = `uname -s`;
print("kernelName = $kernelName\n");
chomp($kernelName);
my $modEncMan = "./simplorer/compiler/modelica/encryptedlibs.manifest";
if(("$kernelName" ne "Linux") and (-f $modEncMan)) {
  print("\nGetting modelica encrypted libraries...\n");
  # grab the modelon encrypted libraries
  my $cmd = "$crappyEBUtool -u $user -p $passwd -s $artUrl $debugSwitch";
  $cmd = "$cmd -m $modEncMan";
  print("\nRunning cmd: $cmd\n");
  my $ret = system($cmd);
  if($ret != 0) {
    $output = "FAILED: 3rdpartyArtifactory failed to extract ";
    $output = "$output modelica encrypted libraries";
    $ret = 1;
    print("\n\n$output in \n\t$cwd\n\n");
    if(! $noXmessage) {
      my $cmd = "xmessage -center \"${output} $cwd\"";
    }
    exit($ret);
  }
} else {
  print("Skipping modelica-encrypted libs\n");
}
print("\nFixing permissions...\n");
$cmd = "chmod -R 775 3rdparty";
my $res = system($cmd);
$output = "SUCCESS: 3rdpartyArtifactory completed in $cwd";
if($res)
{
  $output = "FAILED: failed to $cmd in $cwd";
}
if(! $noXmessage) {
  my $cmd = "xmessage -center \"${output}\"";
}
print("\n\n$output\n\n");
exit($res);
