#! /usr/bin/env perl

use strict;

use Getopt::Long;
use Cwd;
use Cwd 'chdir';
use File::Basename;
use GitModules;

my $branch;
my $j;
my $help;
my $noXmessage = 0;
my $debugMode;
my $help;

GetOptions("branch=s" => \$branch,
           "j:i" => \$j, #run commands in parallel
           "noxmessage" => \$noXmessage, #disable xmessage
           "debugMode" => \$debugMode, 
           "help|?" => \$help
    ) or printHelp();

printHelp() if($help);

sub printHelp
{
  print("\ncheckOutRemoteBranch [-help|?] --branch <name>\n");
  print("\n\tThis script will checkout the remote branch with \"");
  print("branch name\" \n\tif it exists in any of the repos.\n");
  print("\tIf the remote branch does not exist in the repo, the script ");
  print("will\n\tcheckout develop. NOTE: this script does NOT update ");
  print("the repo but does\n\tdo a fetch\n\n");
  exit 1;
}

printHelp() if($help);

if(!$branch) {
  print("\n\nERROR: no branch name given.\n");
  printHelp();
}

print("\nChecking out branch $branch where it exists\n\n");

my $fail = GitModules::runCmd(\&checkOutBranch, $j, $debugMode);

sub checkOutBranch {
  my $dir = $_[0];
  chdir($dir) or die("\nERROR: could not chdir to $dir.\n\n");
  my $currentBranch = qx/cd $dir; git symbolic-ref --short HEAD/;
  chomp($currentBranch);
  if($currentBranch eq $branch) {
    print("$dir is already on $branch. skipping...\n\n");
    return(0);
  }
  print("Fetching all remote branches for $dir\n");
  my $cmd = "cd $dir; git fetch --progress";
  system($cmd) == 0 or die("\nERROR: could not fetch from $dir\n\n");
  $cmd = "cd $dir; git branch -r | grep \"origin/${branch}\$\"";
  my $output = qx/$cmd/;
  chomp($output);
  if(!$output) {
    print("\n$dir does not have remote branch $branch. skipping...\n\n");
    return(0);
  }
  print("$dir is currently on $currentBranch, checking out $branch\n");
  $cmd = "cd $dir; git checkout $branch";
  system($cmd) == 0 or die("\nERROR: could not checkout $branch\n\n");
  print("$dir successfully checked out $branch\n\n");
  return(0);
}

if(!$fail) {
  print("\n\nSuccess\n\n");
} else {
  print("\n\nFAILED\n\n");
}
