#! /usr/bin/env perl

use strict;

use Getopt::Long;
use Cwd;
use Cwd 'chdir';

my $help;
my $url = "ssh://tfs.ansys.com:22/tfs/ANSYS_EBU_Collection/EBU/_git";

GetOptions("url=s" => \$url, #URL to use
           "help|?" => \$help,
    ) or printHelp();

printHelp() if($help);

sub printHelp
{
  print("\ngitStatus [--url <URL>] [--all] [-help|?]\n");
  print("\t--url: URL to use, currently set to: \n\t\t$url\n");
  print("\t--help: show this help...\n\n");
  exit 1;
}

my $remoteCmd = "git remote set-url origin ${url}/";
my $checkoutCmd = "git checkout -b develop origin/develop";

my $pwd = getcwd();
my @dirs;
if(chdir(".git")) {
  print("ERROR: this script only works on a set of repo's. To change a ");
  print("single repo\nUse the command:\n\t${remoteCmd}/<repo name>.git\n");
  print("\nThen update the repo and checkout or merge in the ");
  print("develop branch.\n");
} else {
  my @ls = qx/ls -1/;
  chomp(@ls);
  foreach my $dir(@ls) {
    if(chdir("${dir}/.git")) {
      push(@dirs, $dir);
      chdir($pwd);
    }
  }
}

print("INFO: running git clean...\n\n");
my $cleanCmd = "~/gitScripts/gitClean.pl";
system($cleanCmd);

foreach my $dir(@dirs) {
  chomp($dir);
  if("$dir" eq "Core_Addin") {
    print("\nINFO: removing Core_Addin as it has been removed from ssh\n");
    system("rm -rf Core_Addin");
    next;
  }
  if(! chdir($dir)) {
    print("\nERROR: failed to chdir to $dir\n\n");
    exit 1;
  }
  my $here = getcwd();
  print("Updating $here:\n");
  my $cmd = "git remote -v | grep \"tfs\.ansys\.com\" | head -1";
  my $remote = qx/$cmd/;
  chomp($remote);
  if($remote ne "") {
    print("\n$here is already on TFS, skipping...\n");
    chdir($pwd);
    next;
  }
  $cmd = "${remoteCmd}${dir}.git";
  if(system($cmd)) {
    print("\nERROR: $cmd failed in $here\n\nFAILED....\n");
    exit 2;
  }
  $cmd = "git fetch";
  if(system($cmd)) {
    print("\nERROR: $cmd failed in $here\n\nFAILED....\n");
    exit 3;
  }
  $cmd = "git branch | grep \"^\*\" | awk '{print \$2}'";
  my $branch = qx@$cmd@;
  chomp($branch);
  print("\nbranch = $branch\n");
  if("$branch" eq "master") {
    print("\nChecking out develop\n");
    if(system($checkoutCmd)) {
      print("\nERROR: $checkoutCmd failed in $here\n\nFAILED....\n");
      exit 3;
    }
  } else {
    print("\nINFO: this repo is not on master, you'll need to merge");
    print(" develop into this branch\n");
  }
  print("\nSuccessfully updated $dir\n");
  print("\n\n");
  chdir($pwd);
}
print("\nSuccessfully updated the repo's to $url\n\n");
