#! /usr/bin/env perl

use strict;

use GitModules;

use Cwd;
use Cwd 'chdir';

sub run {
  my $here = $_[0];
  if(!chdir($here)) {
    print("\nERROR: cannot chdir to $here\n\n");
    return(1);
  }
  print("\nDeleting HEAD in $here\n");
  my $command = "cd $here; rm .git/refs/remotes/origin/HEAD";
  system($command);
  return(0);
}

my $fail = GitModules::runCmd(\&run, 1, 0);

if(!$fail) {
  print("\n\ndeleteGitRefs completed successfully\n\n");
} else {
  print("\n\nndeleteGitRefs FAILED\n\n");
}
