#! /usr/bin/env perl

use strict;

use Getopt::Long;
use Cwd;
use Cwd 'chdir';

my $pwd = getcwd();
print("pwd = $pwd\n");

my $help;


GetOptions("help|?" => \$help,
    );

printHelp() if($help);

sub printHelp
{
  print("\ngitCreateBranch [-help|?] <branch name>\n");
  print("\t<branch name>\n");
  print("\n\tThis script will create a new branch with \"");
  print("branch name\" \n\tand push the new branch to origin with ");
  print("tracking.\n\n");
  exit;
}

if(! $ARGV[0]) {
  print("\n\nERROR: no branch name given.\n");
  printHelp();
}

print("\n\nCreating branch $ARGV[0] and pushing to origin with tracking\n\n");
my @cmd = ("git checkout -b $ARGV[0] 2>&1",
           "git push -u origin $ARGV[0] 2>&1",
           "git branch -vv 2>&1");
foreach my $cmd(@cmd) {
  print("\nRunning command: $cmd\n\n");
  my @gitRet = qx/$cmd/;
  chomp(@gitRet);
  foreach my $line(@gitRet) {
    if($line !~ m/igncr/) {
      print("$line\n");
    }
  }
  if($?) {
    print("\n\nERROR: $cmd failed\n\n");
    exit(3);
  } else {
    print("\n\nSUCCESS: $cmd complete\n\n");
  }
}
