#! /usr/bin/env perl

use strict;

use Getopt::Long;
use Cwd;
use Cwd 'chdir';

use threads;
use Thread::Queue;

# create a shared queue
my $queue = Thread::Queue->new();
my $endOfQueueMarker = "ENDOFQUEUEMARKER";
my $failedDirsQueue = Thread::Queue->new();
my $pwd = getcwd();

my $branchName;
my $j;
my $noXmessage;
my $help;

GetOptions("branchName=s" => \$branchName,
           "j:i" => \$j,
           "noXmessage" => \$noXmessage,
           "help|?" => \$help);
printHelp() if($help);

if($branchName eq "") {
  print("\nERROR: must provide a branch name\n");
  printHelp();
  exit(2);
}

sub checkout {
  if(!chdir($pwd)) {
    print("\nERROR: cannot chdir to $pwd\n\n");
    return 1;
  }
  my $error = "0";
  my $done = "0";
  while(!$done) {
    my $dir = $queue->dequeue();
    #print("dir = $dir\n");
    if(defined($dir) && ($dir ne $endOfQueueMarker)) {
      my $cmd;
      my $here = "${pwd}/${dir}";
      if($dir eq ".") {
        $here = $pwd;
      }
      if(!-d($here)) {
        print("ERROR: $here is not a directory\n");
        return 1;
      }
      my $cmd = "cd $here; git ls-remote origin $branchName | grep $branchName";
      my $originBranch = qx/$cmd/;
      if($originBranch eq "") {
        print("\nERROR: $branchName not found on origin\n");
        ++$error;
        $failedDirsQueue->enqueue($cmd);
      } else {
        print("\n$branchName found on origin.\n");
        print("Checking $branchName out in ${dir}\n");
        $cmd = "cd $here; git checkout $branchName";
        if(system($cmd)) {
          print("\nERROR: $cmd failed in repo $dir\n\n");
          ++$error;
          $failedDirsQueue->enqueue($cmd);
        }
      }
    } else {
      return $error;
    }
  }
}
  
sub printHelp {
  print("\ngitCheckoutBranch --branchName <branchName> [--noXmessage]");
  print(" [--help|?]\n");
  print("\t--branchName: name of branch to checkout, required\n");
  print("\t-j: specify number of processors to use, 0 implies all\n");
  print("\t--noXmessage: suppress Xmessage\n");
  print("\t--help|?: print help\n\n");
  exit(0);
}

# figure out how many processors
my $numProc = $ENV{NUMBER_OF_PROCESSORS};
if(defined($j) && ($j != 0)) {
  $numProc = $j;
} else {
  if(defined($numProc)) {
    print("$numProc processors detected\n");
  } else {
    print("cannot determine numb of processors, using 4\n");
    $numProc = "4";
  }
}

# find all repo's
my $numRepos = "0";
if(chdir(".git")) {
  chdir($pwd);
  $queue->enqueue(".");
  ++$numRepos;
} else {
  my @ls = qx/ls -1/;
  chomp(@ls);
  foreach my $dir(@ls) {
    if(chdir("${dir}/.git")) {
      $queue->enqueue("$dir");
      ++$numRepos;
      chdir($pwd);
    }
  }
}
print("numRepos = $numRepos\n");
if($numRepos eq "0") {
  print("No repositories found in $pwd\n\n");
  exit 2;
}

for(my $count = 0; $count < $numRepos; ++$count) {
  $queue->enqueue($endOfQueueMarker);
}

# create a thread per cpu up to numProc or numb of repos
my @myThreads;
for(my $count = "0"; (($count < $numProc) &&
                      ($count < $numRepos)); ++$count) {
  print("Creating queue $count\n");
  $myThreads[$count] = threads->new(\&checkout);
}

# wait for threads to finish
$| = 1;
my $fail = "0";
my $done = "0";
while(!$done) {
  my $numReposLeft = "0";
  $done = "1";
  sleep("1");
  for(my $count = 0; (($count < $numProc) && 
                      ($count < $numRepos)); ++$count) {
    if(!$myThreads[$count]->is_joinable()) {
      ++$numReposLeft;
      $done = "0";
    }
  }
  print("$numReposLeft ");
}

# reap all the myThreads unless we already timed out
if(!$fail) {
  for(my $count = 0; (($count < $numProc) && 
                      ($count < $numRepos)); ++$count) {
    my $ret = $myThreads[$count]->join();
    if($ret) {
      print("\n\nERROR: update failed\n\n");
      $fail = "1";
    }
  }
}
if(!$noXmessage && (-f "/usr/bin/xmessage")) {
  my $output;
  if(!$fail) {
    $output = "SUCCESS: ";
  } else {
    $output = "FAILED: ";
  }
  my $cmd = "xmessage -center \"${output}git update in $pwd\"";
  system($cmd);
}
if(!$fail) {
  print("\n\nUpdate completed successfully\n\n");
  exit 0;
} else {
  print("\n\nUpdate FAILED\n\n");
  print("Failed commands:\n");
  my $errDone = "0";
  while(!$errDone) {
    if(defined(my $err = $failedDirsQueue->dequeue_nb())) {
      print("\t$err\n");
    } else {
      $errDone = "1";
    }
  }
  exit 1;
}
