#! /usr/bin/env perl

use strict;

use Getopt::Long;
use Cwd;
use Cwd 'chdir';

my $noxmessage;
my $forceMerge;
my $noMergeMainBranch;
my $noCommitMerge;
my $pushMerge;
my $j;
my $help;

GetOptions("noxmessage" => \$noxmessage,
           "forceMerge" => \$forceMerge,
           "noMergeMainBranch" => \$noMergeMainBranch,
           "noCommitMerge" => \$noCommitMerge,
           "pushMerge" => \$pushMerge,
           "j:i" => \$j,
           "help|?" => \$help,
    ) or printHelp();

if($help) {
  printHelp();
}

sub printHelp
{
  print("\ngitUpdate [--noxmessage] [--noMergeMainBranch] [--j <int>] ");
  print("[--noCommitMerge] \n\t\t[--pushMerge] [--forceMerge] [--help]\n\n");
  print("Update a set of repo's or just a single repo. Default is to\n");
  print("automerge any non-master branches with master unless this script\n");
  print("is run in a single repo (like simplorer).\n");
  print("\t--noxmessage: suppress xmessage\n");
  print("\t--forceMerge: do the merge even if in a repo\n");
  print("\t--noMergeMainBranch: if a branch is not on main branch (master");
  print("\n\t\tdevelop), don't merge. ");
  print("Default is to merge master into\n\t\tbranch\n");
  print("\t--noCommitMerge: if there are automerged changes, don't commit ");
  print(" them.\n\t\t default behavior is to commit but not push\n");
  print("\t--pushMerge: if changes are automerged, push them.\n");
  print("\t--j <int>: set parallel limit, default is all cpu's\n");
  print("\t--help: print help\n");
  exit 1;
}

my $pwd = cwd();
my $fail = 0;
my $output;


my $pushMergeSw = " ";
if($pushMerge) {
  $pushMergeSw = "--pushMerge";
}
my $commitMergeSw = "--commitMerge";
if($noCommitMerge) {
  $commitMergeSw = "";
  $pushMergeSw = " ";
}
my $mergeMainBranchSw = "--mergeMainBranch";
if($noMergeMainBranch) {
  $mergeMainBranchSw = " ";
  $commitMergeSw = " ";
  $pushMergeSw = " ";
}
if(-d ".git") {
  if(! $forceMerge) {
    # don't merge if we're in a repo, only merge if above
    $mergeMainBranchSw = " ";
    $commitMergeSw = " ";
    $pushMergeSw = " ";
  }
}

my $jSw = " ";
if(defined($j) && ($j != 0)) {
  $jSw = "-j $j";
}

my $cmd = "~/gitScripts/gitFetch.pl --pull --all --noxmessage";
$cmd = "$cmd $mergeMainBranchSw $commitMergeSw $pushMergeSw $jSw";
my $res = system($cmd);
print("\n$cmd returned $res\n");
if($res)
{
  $fail = 1;
  $output = "Update FAILED: $cmd failed in $pwd";
  printAndExit();
}

if(chdir(".git")) {
  # we're in a git repo, don't run the 3rdparty stuff
  $output = "Update SUCCEEDED in $pwd";
  printAndExit();
}

$cmd = "~/gitScripts/3rdpartyArtifactory";
$res = system($cmd);
print("\n$cmd returned $res\n");
if($res)
{
  $output = "Update FAILED: $cmd failed in $pwd";
  $fail = 1;
  printAndExit();
}
$output = "Update SUCCEEDED in $pwd";
printAndExit();



sub printAndExit
{
  print("\n$output\n\n");
  if(!$noxmessage && (-f "/usr/bin/xmessage")) 
  {
    my $cmd = "xmessage -center \"${output}\"";
    system($cmd);
  }
  exit($fail);
}
