#! /usr/bin/env perl

use strict;

use GitModules;

use Getopt::Long;
use Cwd;
use Cwd 'chdir';
use File::Basename;

my $scriptName = basename($0);

my $retries = 4;
my $j;
my $help;
my $debugMode;

GetOptions("r:i" => \$retries, 
           "j:i" => \$j, #run commands in parallel
           "debugMode" => \$debugMode, 
           "help|?" => \$help,
    ) or printHelp();

printHelp() if($help);

print("\n");

sub printHelp {
  print("\n$scriptName [--j [numb]][--help|?]\n");
  print("\t--j [numb]: run commands in parallel\n");
  print("\t--debugMode: turn on debugMode (off by default)\n");
  print("\n\n");
  exit;
}

sub run {
  my $here = $_[0];
  if(!chdir($here)) {
    print("\nERROR: cannot chdir to $here\n\n");
    return(1);
  }
  my $count = 0;
  print("\nRunning $scriptName in $here\n");
  while($count < $retries) {
    my $command = "git fetch --progress";
    print("Running $command in $here, count = $count\n");
    if(system($command)) {
      print("\n$scriptName failed in $here, count = $count\n");
      ++$count;
      if($count >= $retries) {
        print("\n$scriptName failed all retries in $here, count = $count\n");
        return(2);
      }
    } else {
      $count = $retries;
    }
  }
  return(0);
}

my $fail = GitModules::runCmd(\&run, $j, $debugMode);

if(!$fail) {
  print("\n$scriptName completed successfully\n\n");
} else {
  print("\nERROR: $scriptName FAILED\n\n");
}
