#! /usr/bin/env perl

use strict;

use GitModules;

use Getopt::Long;
use Cwd;
use Cwd 'chdir';

my $retries = 4;
my $j;
my $help;
my $debugMode;

GetOptions("r:i" => \$retries, 
           "j:i" => \$j, #run commands in parallel
           "debugMode" => \$debugMode, 
           "help|?" => \$help,
    ) or printHelp();

printHelp() if($help);

print("\n");

sub printHelp {
  print("\nnewGitFetch [--j [numb]][--help|?]\n");
  print("\t--j [numb]: run commands in parallel\n");
  print("\t--debugMode: turn on debugMode (off by default)\n");
  print("\n\n");
  exit;
}

sub run {
  my $here = $_[0];
  if(!chdir($here)) {
    print("\nERROR: cannot chdir to $here\n\n");
    return(1);
  }
  my $count = 0;
  print("\nRunning git fetch in $here\n");
  while($count < $retries) {
    my $command = "git fetch --progress";
    if(system($command)) {
      print("\nFetch failed in $here\n");
      ++$count;
      if($count >= $retries) {
        print("\nFetch failed all retries in $here\n");
        return(2);
      }
    } else {
      $count = $retries;
    }
  }
  return(0);
}

my $fail = GitModules::runCmd(\&run, $j, $debugMode);

if(!$fail) {
  print("\n\newGitFetch completed successfully\n\n");
} else {
  print("\n\nnewGitFetch FAILED\n\n");
}
