#! /usr/bin/env perl

use strict;

use Getopt::Long;
use Cwd;
use Cwd 'chdir';

my $regex;
my $kill;
my $help;

GetOptions("kill" => \$kill, 
           "help|?" => \$help);

if($help) {
  printHelp();
  exit(0);
}

sub printHelp
{
  print("\nprintProcessByNameRegex [--kill ] [--help|?] <name regex>\n");
  print("\n\tThis script will print all the windows processes that ");
  print("regex match the name\n");
  print("\t--kill: this will also kill the processes found\n\n\n");
}

if(! $ARGV[0]) {
  print("\n\nERROR: no regex name given.\n");
  printHelp();
  exit(1);
}
$regex = $ARGV[0];

my $cmd = "tasklist.exe | grep \"$regex\"";
print("\nrunning cmd: $cmd\n");
my @processList = qx/$cmd/;
chomp(@processList);
foreach my $process(@processList) {
  print("$process\n");
}
my @
#tasklist.exe | grep git | awk '{print $2}' | xargs -n 1 taskkill /F /PID
