#! /usr/bin/env perl

use strict;

use Getopt::Long;
use Cwd;
use Cwd 'chdir';
use File::Basename;

my @files = qx/ls --color=no -1/;
chomp @files;
my $fail = 0;
foreach my $file(@files) {
  my $oldName = $file;
  $file =~ s/ .*//;
  my $cmd = "mv \"$oldName\" $file";
  print("\t$cmd\n");
  if(system($cmd)) {
    print("\nERROR: $cmd failed\n");
    $fail = 1;
  }
}
if($fail) {
  print("\nFAILED\n");
  exit(1);
}
print("\nSUCCESS\n");
exit(0);
