#! /usr/bin/env perl
use strict;

use Getopt::Long;
use Cwd;
use Cwd 'chdir';

my @libs = qx/ls -1/;
chomp(@libs);
my $error = 0;
foreach my $file(@libs) {
  my @tokens = split(/ /, $file);
  my $cmd = "mv \"$file\" $tokens[0]";
  print("Exec'ing $cmd\n");
  if(system($cmd)) {
    print("\nERROR: cmd: $cmd FAILED\n");
    ++$error;
  }
}
if($error) {
  print("\nFAILED: convert failed\n");
} else {
  print("\nSuccess\n");
}
    
