#! /usr/bin/env bash

if [[ -z $(git status -uno -s) ]]; then
    echo "tree is clean"
    exit 0
else
    echo
    echo -n "tree is dirty: "
    basename $(git rev-parse --show-toplevel)
    git status -uno -s
    echo
    exit 3
fi
