#! /usr/bin/env perl                                                            

use strict;

use GitModules;

use Getopt::Long;
use Cwd;
use Cwd 'chdir';
use File::Basename;

my $scriptName = basename($0);
my $j;
my $help;
my $debugMode;

GetOptions("j:i" => \$j, #run commands in parallel
           "debugMode" => \$debugMode,
           "help|?" => \$help,
    ) or printHelp();

printHelp() if($help);

print("\n");

sub printHelp {
  print("\nThis script will delete all the HEAD refs from any repo's it ");
  print("can find. it will\nthen run git gc, then git fetch.\n");
  print("So when this is finished all repo's will be up to date with ");
  print("origin (though\nthe branch will not be merged up).\n");
  print("\n$scriptName [--j [numb]][--help|?]\n");
  print("\t--j [numb]: run commands in parallel\n");
  print("\t--debugMode: turn on debugMode (off by default)\n");
  print("\n\n");
  exit;
}

sub run {
  my $here = $_[0];
  if(!chdir($here)) {
    print("\nERROR: cannot chdir to $here\n\n");
    return(1);
  }
  print("\nRunning $scriptName in $here\n");
  my $command = "cd $here; deleteGitRefs";
  if(system($command)) {
    print("\n$command failed in $here\n");
    return(1);
  }
  $command = "cd $here; git gc";
  if(system($command)) {
    print("\n$command failed in $here\n");
    return(1);
  }
  $command = "cd $here; newGitFetch";
  if(system($command)) {
    print("\n$command failed in $here\n");
    return(2);
  }
  return(0);
}

my $fail = GitModules::runCmd(\&run, $j, $debugMode);

if(!$fail) {
  print("\n$scriptName completed successfully\n\n");
} else {
  print("\nERROR: $scriptName FAILED\n\n");
}
