#! /usr/bin/env perl

use strict;

use Getopt::Long;
use Cwd;
use Cwd 'chdir';
use File::Basename;

my $j;
my $help;
my $noXmessage = 0;

use threads;
use Thread::Queue;

# create a shared queue
my $queue = Thread::Queue->new();
my $endOfQueueMarker = "ENDOFQUEUEMARKER";
my $tempDir = $ENV{TEMP};

my $repoTarDir = "repoTarFiles";

GetOptions("help|?" => \$help,
    ) or printHelp();

printHelp() if($help);

sub printHelp
{
  print("\nunTarRepos [-j <numb>] [-help|?]\n");
  print("\n\tThis script will tar up all repo's in the directory and ");
  print("store the files in $tempDir/$repoTarDir\n\n");
  exit 1;
}

printHelp() if($help);
my $pwd = getcwd();
my $repoTarDirFull = "$tempDir/$repoTarDir";
if(!chdir($repoTarDirFull)) {
  print("\nERROR: $repoTarDirFull does not exist\n\n");
  exit 4;
}

my $numRepos = "0";
my @ls = qx/ls -1 *.tgz/;
chomp(@ls);
foreach my $tgz(@ls) {
  $tgz =~ s/\.tgz//;
  print("queuing $tgz\n");
  $queue->enqueue("$tgz");
  ++$numRepos;
}
print("numRepos = $numRepos\n");
if($numRepos eq "0") {
  print("No tar files found in $pwd\n\n");
  exit 2;
}

# figure out how many processors
my $numProc = $ENV{NUMBER_OF_PROCESSORS};
if(defined($j) && ($j != 0)) {
  $numProc = $j;
} else {
  if(defined($numProc)) {
    print("$numProc processors detected\n");
  } else {
    print("cannot determine numb of processors, using 4\n");
    $numProc = "4";
  }
}

if((!defined($numProc)) || ($numProc == 0)) {
  $numProc = 1;
}

for(my $count = 0; $count < $numRepos; ++$count) {
    $queue->enqueue($endOfQueueMarker);
}

# create a thread per cpu up to numProc or numb of repos
my @myThreads;
for(my $count = "0"; (($count < $numProc) &&
                      ($count < $numRepos)); ++$count) {
  print("Creating queue $count\n");
  $myThreads[$count] = threads->new(\&runCmd);
}

# wait for threads to finish
$| = 1;
my $done = "0";
while(!$done) {
  my $numReposLeft = "0";
  $done = "1";
  sleep("1");
  for(my $count = 0; (($count < $numProc) && 
                      ($count < $numRepos)); ++$count) {
    if(!$myThreads[$count]->is_joinable()) {
      ++$numReposLeft;
      $done = "0";
    }
  }
  if($numProc > 1) {
    print("$numReposLeft ");
  }
}

# reap all the myThreads

my $fail = "0";
for(my $count = 0; (($count < $numProc) && 
                    ($count < $numRepos)); ++$count) {
  my $ret = $myThreads[$count]->join();
  if($ret) {
    print("\nERROR: unTarRepos failed\n\n");
    $fail = "1";
  }
}
if(!$noXmessage && (-f "/usr/bin/xmessage")) {
  my $output;
  if(!$fail) {
    $output = "SUCCESS: ";
  } else {
    $output = "FAILED: ";
  }
  my $cmd = "xmessage -center \"${output}unTarRepos in $pwd\"";
  system($cmd);
}
if(!$fail) {
  print("\n\nunTarRepos completed successfully\n\n");
} else {
  print("\n\nunTarRepos FAILED\n\n");
}

sub runCmd {
  if(!chdir($pwd)) {
    print("\nERROR: cannot chdir to $pwd\n\n");
    return 1;
  }
  my $error = "0";
  my $done = "0";
  while(!$done) {
    my $repo = $queue->dequeue();
    print("repo = $repo\n");
    if(defined($repo) && ($repo ne $endOfQueueMarker)) {
      my $cmd = "tar -xzf $repoTarDirFull/$repo.tgz";
      if(system($cmd)) {
        print("\nERROR: failed to unTar $repo\n");
        return 1;
      }
      print("\n$repo complete\n");
    } else {
      return 0;
    }
  }
}
