#! /usr/bin/env perl

use strict;

use Getopt::Long qw(:config pass_through);
use Cwd;
use Cwd 'chdir';

my $currentDir = getcwd();

my $vsDir = "/cygdrive/c/Program\ Files\ \(x86\)/Microsoft\ Visual\ Studio\ 11.0/Common7/IDE";
#my $vsDir = "/cygdrive/c/Program\\ Files\\ \\(x86\\)/Microsoft\\ Visual\\ Studio\\ 11.0/Common7/IDE";
if(!chdir($vsDir)) {
  print("ERROR: cannot chdir to $vsDir\n\n");
  exit 2;
}
my $pwd = getcwd();
print("pwd = $pwd\n");
my $vsExec = "devenv.exe";
if(! -e $vsExec) {
  print("ERROR: cannot find $vsExec exec\n\n");
  exit 1;
}
$ENV{MODELICA_PERFORMANCE_ENV_VALUE} = "1";
print("MODELICA_PERFORMANCE_ENV_VALUE = $ENV{MODELICA_PERFORMANCE_ENV_VALUE}\n");
system("./$vsExec &> /tmp/crap.out &");
